### ISSUE TITLE
failed to run custom build command for `carla-sys v0.11.1`

### ISSUE THREAD

**Issue by xiaoc88** [evshary/autoware_carla_launch#103]
Hi, I ran into an issue where Cara-sys would not build.
command: make build_bridge
error:
![image](https://github.com/evshary/autoware_carla_launch/assets/170789842/dff89470-1e1d-4490-8a8e-b4d8eafc6e39)

Or always in such a state:
![image](https://github.com/evshary/autoware_carla_launch/assets/170789842/60b81c7f-778c-4c0b-b23e-3c97cce0d36f)

The following methods have been tried but still cannot be solved:
1. Replace Cargo.toml with the link content
https://github.com/evshary/zenoh_carla_bridge/blob/main/Cargo.lock#L853
2. Delete Cargo.lock
3. https://github.com/evshary/autoware_carla_launch/issues/52

**Comment by evshary** [comment]
Hi @xiaoc88 It seems like you can't download the artifact from GitHub. Could you try to ping / wget the data from GitHub?

**Comment by xiaoc88** [comment]
@evshary Is my side of the problem,Clean the carla bridge container，and then compile a few more times can be, thank you.
