### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by zeidk** [evshary/autoware_carla_launch#11]
Hello,
just wanted to point out that I had to install cargo to be able to follow the build steps from the documentation.

sudo apt install cargo

**Comment by evshary** [comment]
In fact, the installation script should help you install Rust, which includes `cargo`
https://github.com/evshary/autoware_carla_launch/blob/main/dependency_install.sh#L13
Maybe you can try to relaunch the terminal after `make prepare`
I guess Rust environment variables will be loaded after relaunching the terminal.
