### ISSUE TITLE
build problem: can not pull ghcr.io/autowarefoundation/autoware-universe:galactic-20221201-prebuilt-cuda-amd64 image

### ISSUE THREAD

**Issue by LifeIsBinary** [evshary/autoware_carla_launch#116]
following [Documentation](https://autoware-carla-launch.readthedocs.io/en/latest/) ,
when  [Build the container for Carla bridge](https://autoware-carla-launch.readthedocs.io/en/latest/build.html#build-the-container-for-carla-bridge),

I can not pull ghcr.io/autowarefoundation/autoware-universe:galactic-20221201-prebuilt-cuda-amd64 image.

After login ghcr.io by github account (following  https://stackoverflow.com/questions/74656167/unable-to-pull-image-from-github-container-registry-ghcr
), I still getting the message, "Error response from daemon: denied", when docker pull.

**Comment by evshary** [comment]
AWF switched the place storing docker image. We couldn't download the old images temporarily.
We need to wait for their update.
Here is the discussion: https://github.com/orgs/autowarefoundation/discussions/4964

**Comment by evshary** [comment]
Hi @LifeIsBinary @MamoruDS, the issue should be solved by https://github.com/evshary/autoware_carla_launch/pull/122
Let me know if there is any other issue.

**Comment by evshary** [comment]
I'll close the issue. Feel free to reopen it if there is any further problem.
