### ISSUE TITLE
How to expand the number of vehicles

### ISSUE THREAD

**Issue by YangXianqi** [evshary/autoware_carla_launch#120]
Now, the number of presented vehicles with autowares are set to 2. How to expend the number?

**Comment by evshary** [comment]
Hi @YangXianqi, You can update the script here and spawn more vehicles as you wish. (Note the vehicle name)
https://github.com/evshary/autoware_carla_launch/blob/main/script/run-bridge-two-vehicles-v2x.sh
Then you can run more Autoware with different names.

**Comment by evshary** [comment]
I'll close the issue. Feel free to reopen it if there is any further problem.
