### ISSUE TITLE
Obstacle avoidance with lane change

### ISSUE THREAD

**Issue by zeidk** [evshary/autoware_carla_launch#22]
Hello,
this is not an issue and the question has nothing to do with your project. I couldn't find any answer so I wanted to check if someone knowledgeable may know the answer. When there is an obstacle in the same lane as the ego vehicle, the ego vehicle stops behind the obstacle. Do I have to do something specific for the ego vehicle to change lane instead of stopping?

Thank you

**Comment by evshary** [comment]
I'm not familiar with the topic, but I found the discussion. Maybe it could answer your question.
https://github.com/orgs/autowarefoundation/discussions/3698

**Comment by zeidk** [comment]
Thank you very much for pointing to the thread.
