### ISSUE TITLE
humble branch is Failed to enter Docker

### ISSUE THREAD

**Issue by Autostone-c** [evshary/autoware_carla_launch#23]
![image](https://github.com/evshary/autoware_carla_launch/assets/50130211/b9cab0c0-750d-4b82-aef6-be03cfec5b11)

I follow the README.md. and I have already apt install tmux inetutils-ping vim.

**Comment by evshary** [comment]
I believe the issue came from the docker cache.
Please do `docker system prune` and try again.

BTW, I saw you tried to use galactic with containers. There is some issue with galactic in container.
Suggest using humbe in the container instead, or running galactic in your native host.

**Comment by Autostone-c** [comment]
> I believe the issue came from the docker cache. Please do `docker system prune` and try again.
> 
> BTW, I saw you tried to use galactic with containers. There is some issue with galactic in container. Suggest using humbe in the container instead, or running galactic in your native host.

i will try it. by the way, i follow your README.md. and i see the run-bridge-docker.sh(humble branch) use galactic
![image](https://github.com/evshary/autoware_carla_launch/assets/50130211/81825ee4-9dda-4454-a97b-17bf76257389)
![image](https://github.com/evshary/autoware_carla_launch/assets/50130211/3f3dd371-c6cc-4a44-84bb-c94a87f5b18b)

**Comment by evshary** [comment]
Oh, I see. Then that's fine though, since the bridge still depends on some galactic ROS packages.
If Autoware is running on humble, then it's OK.

**Comment by Autostone-c** [comment]
> Oh, I see. Then that's fine though, since the bridge still depends on some galactic ROS packages. If Autoware is running on humble, then it's OK.

have you ever try run this work on two machine？for example (carla on x86 workstation and autoware-humble on Nvidia Jetson Orin)

**Comment by Autostone-c** [comment]
hi, I have encountered the following error, can you help me
![image](https://github.com/evshary/autoware_carla_launch/assets/50130211/06047c94-82a2-4917-9e7d-5f03f69010ca)

**Comment by evshary** [comment]
> > Oh, I see. Then that's fine though, since the bridge still depends on some galactic ROS packages. If Autoware is running on humble, then it's OK.
> 
> have you ever try run this work on two machine？for example (carla on x86 workstation and autoware-humble on Nvidia Jetson Orin)

It definitely can run on two machines. This is one of the purposes of the projects.
However, I haven't tried Autoware Humble in Jetson Orin and don't know whether there is any issue.

**Comment by evshary** [comment]
> hi, I have encountered the following error, can you help me ![image](https://user-images.githubusercontent.com/50130211/258076882-06047c94-82a2-4917-9e7d-5f03f69010ca.png)

Maybe you can make sure [Autoware in docker](https://autowarefoundation.github.io/autoware-documentation/main/installation/autoware/docker-installation-prebuilt/) can run in your environment first.
It seems like there are some issues for your container to use GPU.

**Comment by Autostone-c** [comment]
> > hi, I have encountered the following error, can you help me ![image](https://user-images.githubusercontent.com/50130211/258076882-06047c94-82a2-4917-9e7d-5f03f69010ca.png)
> 
> Maybe you can make sure [Autoware in docker](https://autowarefoundation.github.io/autoware-documentation/main/installation/autoware/docker-installation-prebuilt/) can run in your environment first. It seems like there are some issues for your container to use GPU.

im trying it? can i have you wechat for communication

**Comment by evshary** [comment]
I prefer to have the discussion here because the issue might also be met by others.
Then they could refer to the discussion.

**Comment by Autostone-c** [comment]
> I prefer to have the discussion here because the issue might also be met by others. Then they could refer to the discussion.

i see, im trying build autoware in docker. and my ultimate goal is Orin(autoware-humble) and carla on x86 workstation

**Comment by evshary** [comment]
> i see, im trying build autoware in docker. and my ultimate goal is Orin(autoware-humble) and carla on x86 workstation

I believe this is feasible, but I have little experience running Autoware in Orin.
Maybe you can take a look at here
https://github.com/orgs/autowarefoundation/discussions/3537

**Comment by Autostone-c** [comment]
> I prefer to have the discussion here because the issue might also be met by others. Then they could refer to the discussion.

hi，i can run it on the same machine now, but The Carla scene remains unchanged with the changes in autoware（no car ， and always like the picture below）
![image](https://github.com/evshary/autoware_carla_launch/assets/50130211/cc573f13-5b80-44ec-a48b-4ea51a09eb13)

**Comment by Kim-mins** [comment]
@Autostone-c 
If you want to follow the driving of the ego vehicle, please provide the option `--pygame` for the [running script](https://github.com/evshary/autoware_carla_launch/blob/humble/script/run-bridge.sh)

**Comment by Autostone-c** [comment]
> @Autostone-c If you want to follow the driving of the ego vehicle, please provide the option `--pygame` for the [running script](https://github.com/evshary/autoware_carla_launch/blob/humble/script/run-bridge.sh)

nice，it really help me. thanks

**Comment by Autostone-c** [comment]
now, im trying run it on two machine(carla on x86 workstation and autoware-humble on Nvidia Jetson Orin)

Expect good results

**Comment by Autostone-c** [comment]
@evshary hi, i try run it on two machine(carla on x86 workstation and autoware-humble on Nvidia Jetson Orin). and i modify the autoware image amd64 to arm64. Nvidia docker run other container has no error.
![image](https://github.com/evshary/autoware_carla_launch/assets/50130211/bf15f04e-4420-45fd-9b3d-dda52324b8e3)

**Comment by evshary** [comment]
Do you install NVIDIA Container Runtime? I'm not familiar with this part, but I'd suggest checking whether you can run containers with NVIDIA GPU first.

**Comment by Autostone-c** [comment]
> Do you install NVIDIA Container Runtime? I'm not familiar with this part, but I'd suggest checking whether you can run containers with NVIDIA GPU first.

yes， i install it. now i delete --nvidia  ,and enter into docker. i want ask if i run two machine, should the configuration file be modified? like ip or some else
