### ISSUE TITLE
How to detect the traffic light in Carla?

### ISSUE THREAD

**Issue by TianYifan-Vincent** [evshary/autoware_carla_launch#82]
Sorry to bother you @evshary , i want to know whether in this bridge, Autoware can recognize the traffic light in Carla and follow the traffic rules.

**Comment by evshary** [comment]
Hi @TianYifan-Vincent, the bridge only passes the camera image to Autoware. We still need to do some configuration in Autoware to be able to recognize the traffic light.

**Comment by TianYifan-Vincent** [comment]
> Hi @TianYifan-Vincent, the bridge only passes the camera image to Autoware. We still need to do some configuration in Autoware to be able to recognize the traffic light.

Thank you so much and your devotion!

**Comment by Justin-Xiang** [comment]
@evshary Hi, Could you provide guidance on configuring Autoware for traffic light recognition? I came across [this section](https://autowarefoundation.github.io/autoware.universe/main/simulator/autoware_carla_interface/#traffic-light-recognition), which mentions modifying the map. Is there a more convenient or accurate method to achieve this? Any advice or best practices would be greatly appreciated!

Thank you!

**Comment by evshary** [comment]
Hi @Justin-Xiang I'm afraid there are no other convenient ways to do so since we still need the traffic light information on the map.
