### ISSUE TITLE
The simulator window displays

### ISSUE THREAD

**Issue by xiaoc88** [evshary/autoware_carla_launch#92]
Hello,How to display the simulation interface during the autonomous driving process?
![2024-05-25_14-32](https://github.com/evshary/autoware_carla_launch/assets/170789842/10ba8d92-4f2e-4a34-b886-aa3e919c144f)

**Comment by evshary** [comment]
You can add `--pygame` while spawning the vehicle into the simulator here
https://github.com/evshary/autoware_carla_launch/blob/main/script/run-bridge.sh#L14

**Comment by xiaoc88** [comment]
@evshary nice,your answer helped me, thank you.
