### ISSUE TITLE
Cannot edit Town01.osm map

### ISSUE THREAD

**Issue by xiaoc88** [evshary/autoware_carla_launch#95]
map tool: https://tools.tier4.jp/vector_map_builder_ll2/
osm map: Town01.osm
error: FileFormatError,Map exists over multiple grid-zones

![2024-05-27_18-46](https://github.com/evshary/autoware_carla_launch/assets/170789842/e02eeaab-f965-4dc2-b3b4-eb6dd9dcac99)

**Comment by evshary** [comment]
Hi @xiaoc88, in fact, the map we're using now is from other project
https://github.com/evshary/autoware_carla_launch/tree/main/carla_map
I didn't do too much research on how to edit the map. I'm afraid I can't give you a proper answer.

**Comment by xiaoc88** [comment]
@evshary Thank you for your answer, should I close this question now?

**Comment by evshary** [comment]
Maybe you can close it. But still feel free to put any other information here if you find the solution. It would be a good reference for others.

**Comment by xiaoc88** [comment]
Okay, I will close this issue first.
